name: 'GitHub Actions Weather Bot'

on:
  push:
    paths:
      - '.github/workflows/weather.yml'
  schedule:
    - cron: '0 3,10,23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Weather'
        run: |
          curl -o result.html wttr.in/Yuhuatai?format="%C%f%w\n"\&m
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}@163.com
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Yuhuatai Weather
          body: file://result.html
          to: ${{secrets.WEATHER_TO}}
          from: my
