name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Weather'
        run: curl -o result.html wttr.in/Yuhuatai?lang=zh-cn
      - name: 'Send mail'
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.163.com
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: my
          from: ${{secrets.MAIL_USERNAME}}@163.com
          subject: Today weather
          body: file://result.html
          attachments: '[{"path":"result.html"}]'
          to: ${{secrets.WEATHER_TO}}
