name: 'GitHub Actions Weather Bot'

on:
  push:
    paths:
      - '.github/workflows/weather.yml'
  schedule:
    - cron: '0 3,10,23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Weather'
        run: |
          curl -o result.html wttr.in/Yuhuatai?format="%C%f%w\n"\&m
      - name: 'Send mail'
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.163.com
          account: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: my
          from: ${{secrets.MAIL_USERNAME}}@163.com
          subject: Yuhuatai weather
          body: file://result.html
          attachments: '[{"path":"result.html"}]'
          to: ${{secrets.WEATHER_TO}}
