name: 'GitHub Actions Weather Bot'

on:
  push:
    paths:
      - '.github/workflows/weather.yml'
  schedule:
    - cron: '0 6 1 * *'

permissions:
  contents: write # 授予 Workflow 写权限以修改仓库内容

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
        # 设置 Git 配置
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # 更新 update.md 文件（示例：追加当前日期）
      - name: Update update.md
        run: |
          echo "Last updated: $(date)" > update.md

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          git add update.md
          git commit -m "Update update.md with latest timestamp"
          git push
      - name: 'Get Weather'
        run: |
          curl -o result.html wttr.in/Yuhuatai?format="%C%f%w\n"\&m\&lang=zh-cn
          echo 'weather_result<<EOF' >> $GITHUB_ENV
          cat result.html >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}@163.com
          password: ${{secrets.MAIL_PASSWORD}}
          subject: 雨花台${{env.weather_result}}
          body: file://result.html
          to: ${{secrets.WEATHER_TO}}
          from: my
